# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039c69039b1e0e7fc07df2cce2057c83da272a5bf13caf5a662b497b3f0cd0f8338247c0f9ae13f0e9022d7d19fdeaef26a4d4c149d3f3de9a9e47db1c23c06e

test:
  secret_key_base: d57adf19422d63e286cbdb27cc776122fe59cec98f7b7040831bb8aac111945941e36da8acda0d3a96caa05925158d5343c1435d37c1ac6dafbe8b4a0027ee78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
